AWSTemplateFormatVersion: 2010-09-09
Description: EC2 built in each of the two AZ. One of the EC2 has Apache installed.

Parameters:
  ProjectNameforEC2:
    Type: String
    Default: cfn

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.small
    Description: Enter t2.micro, t2.small, or t3.small. Default is t2.micro.

Resources: 
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: raisetech-key
      ImageId: ami-0ecb2a61303230c9d
      InstanceType:
        Ref: InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue PublicSecurityGroup
      SubnetId: !ImportValue PublicSubnet1
      UserData: !Base64 |
          #!/bin/bash -ex
          yum -y update
          cp -p /usr/share/zoneinfo/Japan /etc/localtime
          shutdown -h 60
      BlockDeviceMappings: 
        - 
          DeviceName: /dev/xvda
          Ebs: 
              Encrypted: false
              VolumeSize: 8
              VolumeType: gp2
              DeleteOnTermination: true      
      Tags:
        - Key: Name
          Value: !Sub ${ProjectNameforEC2}-ec2-1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: raisetech-key
      ImageId: ami-0ecb2a61303230c9d
      InstanceType:
        Ref: InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue PublicSecurityGroup
      SubnetId: !ImportValue PublicSubnet2
      UserData: !Base64 |
        #!/bin/bash -ex
        yum -y update
        cp -p /usr/share/zoneinfo/Japan /etc/localtime
        yum -y install httpd
        systemctl start httpd.service
        systemctl enable httpd.service
        shutdown -h 60
      BlockDeviceMappings: 
        - 
          DeviceName: /dev/xvda
          Ebs: 
              Encrypted: false
              VolumeSize: 8
              VolumeType: gp2
              DeleteOnTermination: true      
      Tags:
        - Key: Name
          Value: !Sub ${ProjectNameforEC2}-ec2-2-apache

Outputs:
  EC2Instance1:
    Value: !Ref EC2Instance1
    Export:
      Name: EC2Instance1

  EC2Instance2:
    Value: !Ref EC2Instance2
    Export:
      Name: EC2Instance2  
 